### ISSUE TITLE
Specifying epochs instead of steps

### ISSUE THREAD

**Issue by lilakk** [princeton-nlp/ProLong#4]
Hi all, if I want to train for a specific number of epochs rather than steps, is it okay to just set `epoch_size` to None when creating the `SortByLengthDataset` [here](https://github.com/princeton-nlp/ProLong/blob/1e153bbd769943de0ecc4aafc6a1052e0371b32b/training/dataset.py#L144)? Would that cause any issues for the replicated data streaming processes?

**Comment by CodeCreator** [comment]
Yes, I think setting `epoch_size` to `None` should be fine! Alternatively, you can compute the number of steps required for an epoch in advance.

FWIW if you use multiple data sources with different mixture weights, this might cause some repeated samples [according to the streaming documentation](https://docs.mosaicml.com/projects/streaming/en/stable/dataset_configuration/mixing_data_sources.html#using-proportion-for-relative-weighting)

**Comment by lilakk** [comment]
Got it, thanks!
