### ISSUE TITLE
Error while loading ultrachat dataset used in ProLong

### ISSUE THREAD

**Issue by amy-hyunji** [princeton-nlp/ProLong#5]
Hi all, thank you for releasing great work with all the details!

I have an issue downloading the ultrachat 64k dataset used during ProLong SFT (https://huggingface.co/datasets/princeton-nlp/prolong-ultrachat-64K).
```
pyarrow.lib.ArrowInvalid: Struct child array #2 invalid: Invalid: Length spanned by list offsets (95) larger than values array (length 92)
```
this is the error message I get. Do you have a guess on where this error message is coming from?

Thank you!

**Comment by gaotianyu1350** [comment]
Hi,

Our UltraChat dataset is mosaicml-streaming format instead of huggingface dataset format, so you will need to download it using HuggingFace Hub's git function (git clone ...).

**Comment by amy-hyunji** [comment]
Got it! Thanks :)
