### ISSUE TITLE
What's the change to Llama model ?

### ISSUE THREAD

**Issue by wtzhang99** [princeton-nlp/ProLong#6]
What changes are done for `modeling_flash_llama.py` compare with the original EleutherAI version ? Only wrap the attention with deepspeed's `DistributedAttention` ?   Thx!

**Comment by gaotianyu1350** [comment]
Hi,

The main change is (1) add flash rotary embedding, (2) add support to variable length attention, (3) distributed attention, (4) modification on the cross entropy calculation to save memory (similar to the fused cross entropy logic).
